### ISSUE TITLE
rearrange json calls

### ISSUE THREAD

**Issue by blackdotbug** [tkadamson/Oregon-Housing-Dashboard#25]
https://github.com/tkadamson/disheveledmummies-US-social-metrics/blob/497869705386ff5dee2c7dd84480c28a138b5aae/highcharts.js#L15

I think you can rearrange this slightly differently into a promise.all, and have all your buildmap calls in the then after that. 

Your for loop is fine, but instead of making the d3.json call, you can just push the d3.json(countyurl) into a waiting empty array. Once the loop is done, pass the array into a promise all function, then in the then run all your build map calls.

**Comment by tkadamson** [comment]
Changed and working
